apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mydb1
spec:
  replicas: 1
  selector:
    matchLabels:
      team: prod
  template:
    metadata:
      labels:
        team: prod
    spec:
        containers:
        - name: "c1"
          image: "mysql"
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: mypassword
          - name: MYSQL_DATABASE
            value: lwdb
          - name: MYSQL_USER
            value: vimal
          - name: MYSQL_PASSWORD
            value: mypassword

