apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc
spec:
  accessModes:
   - ReadWriteOnce
  resources:
     requests:
        storage: 5Gi
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      team: prod
  template:
    metadata:
      labels:
        team: prod
    spec:
        volumes:
        - name: mysql-pvc1
          persistentVolumeClaim:
           claimName: mysqlpvc
        containers:
        - name: "c1"
          image: "mysql:latest"
          volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-pvc1
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: mysecretbox
                key:  p
          - name: MYSQL_DATABASE
            value: lwdb
          - name: MYSQL_USER
            valueFrom: 
              secretKeyRef:
                name: mysecretbox
                key:  u
          - name: MYSQL_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: mysecretbox
                key:  p

---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  clusterIP: 10.98.153.68
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    team: prod
  type: ClusterIP
